#!/usr/bin/env python3

import argparse
import os

parser = argparse.ArgumentParser(description="CLI for Batching")
parser.add_argument("--cpu", type=int, default=8, help="The number of CPUs")
parser.add_argument("--mem", type=str, default=32, help="The memory in GB")
parser.add_argument("--gpu", type=int, default=2, help="The number of GPUs")
parser.add_argument("--ckpt", type=str, default=None, help="The path to the checkpoint file")

parser.add_argument("model_name", help="The name of the model")
parser.add_argument("image_loss", help="The image loss function, e.g. mse:1")
parser.add_argument("flow_loss", help="The flow loss function, e.g. gl:1")
parser.add_argument("max_epoch", help="The maximum number of epochs")
parser.add_argument("series_len", help="The length of the series")
parser.add_argument("reg_type", help="Volume or time series (volume, series)")

args = parser.parse_args()

# Build bash script
bash_script = f"""#!/bin/bash
#
#SBATCH --job-name=registration_job_gpu
#SBATCH --output=/hpc/scratch/project/jvc-lab/stud/registration/log/registration_{args.model_name}-{args.image_loss}-{args.flow_loss}-{args.max_epoch}-{args.series_len}-{args.reg_type}_out.txt
#SBATCH --error=/hpc/scratch/project/jvc-lab/stud/registration/log/registration_{args.model_name}-{args.image_loss}-{args.flow_loss}-{args.max_epoch}-{args.series_len}-{args.reg_type}_err.txt
#SBATCH --time=7-00:00:00
#
#SBATCH --cpus-per-task={args.cpu}
#SBATCH --mem={args.mem}GB
#SBATCH --partition leinegpu_long
#SBATCH --gres=gpu:{args.gpu}
#SBATCH --mail-user=jamie.temple@stud.hs-hannover.de
#SBATCH --mail-type=ALL

module load Python/3.10.4
source /hpc/scratch/project/jvc-lab/stud/registration/.venv/bin/activate
cd /hpc/scratch/project/jvc-lab/stud/registration/reg
"""

bash_script += (f"python main.py --log --devices {args.gpu} --num_workers {args.cpu} train {args.model_name} "
                f"{args.image_loss} {args.flow_loss} {args.max_epoch} {args.series_len} {args.reg_type}")

if args.ckpt is not None:
    bash_script += f" --path_to_ckpt {args.ckpt}"

# Execute bash script
with open("batch.sh", "w") as f:
    f.write(bash_script)
os.system("sbatch batch.sh")
os.remove("batch.sh")
