#!/bin/bash
#
#SBATCH --job-name=registration_job_gpu
#SBATCH --output=/hpc/scratch/project/jvc-lab/stud/registration/log/registration_job_gpu_out.txt
#SBATCH --error=/hpc/scratch/project/jvc-lab/stud/registration/log/registration_job_gpu_err.txt
#SBATCH --time=7-00:00:00
#
#SBATCH --cpus-per-task=16
#SBATCH --mem=32GB
#SBATCH --partition leinegpu_long
#SBATCH --gres=gpu:1
#SBATCH --mail-user=jamie.temple@stud.hs-hannover.de
#SBATCH --mail-type=ALL

echo "Load module"
module load Python/3.10.4

echo "Change to project"
cd /hpc/scratch/project/jvc-lab/stud/registration

echo "Activate python venv"
source .venv/bin/activate

echo "Prepare for launch"
cd src
nvidia-smi

echo "Launch"
python main.py \
    --devices 2 \
    --max_epochs 100
